#!/bin/bash

# Guide de test complet QuantumShield
echo "🧪 GUIDE DE TEST QUANTUMSHIELD"
echo "=============================="

echo ""
echo "1. 🏠 TEST DE LA PAGE D'ACCUEIL"
echo "   ✅ Accéder à http://localhost:3000"
echo "   ✅ Vérifier l'affichage du hero section"
echo "   ✅ Cliquer sur les boutons 'Commencer' et 'En savoir plus'"

echo ""
echo "2. 🔐 TEST D'INSCRIPTION"
echo "   ✅ Cliquer sur 'S'inscrire'"
echo "   ✅ Remplir: Email, Nom d'utilisateur, Mot de passe"
echo "   ✅ Vérifier la création avec 50 QS + 5 QS bonus"

echo ""
echo "3. 🔑 TEST DE CONNEXION"
echo "   ✅ Se déconnecter et se reconnecter"
echo "   ✅ Vérifier la redirection vers le dashboard"

echo ""
echo "4. 📊 TEST DU DASHBOARD"
echo "   ✅ Vérifier l'affichage du solde QS"
echo "   ✅ Voir les statistiques des dispositifs"
echo "   ✅ Contrôler le feed d'activité"

echo ""
echo "5. 📱 TEST DES DISPOSITIFS IoT"
echo "   ✅ Aller dans 'Dispositifs'"
echo "   ✅ Enregistrer un Smart Sensor (+10 QS)"
echo "   ✅ Enregistrer une Security Camera (+10 QS)"
echo "   ✅ Enregistrer un Smart Thermostat (+10 QS)"
echo "   ✅ Envoyer des heartbeats (+1 QS par dispositif)"
echo "   ✅ Changer les statuts (Actif/Maintenance/Inactif)"

echo ""
echo "6. 🔐 TEST DE LA CRYPTOGRAPHIE"
echo "   ✅ Aller dans 'Cryptographie'"
echo "   ✅ Générer une paire de clés NTRU++ 2048-bit"
echo "   ✅ Chiffrer un message de test"
echo "   ✅ Déchiffrer le message"
echo "   ✅ Créer une signature numérique"
echo "   ✅ Vérifier la signature"
echo "   ✅ Voir les métriques de performance"

echo ""
echo "7. 💰 TEST DU SYSTÈME DE TOKENS"
echo "   ✅ Aller dans 'Tokens'"
echo "   ✅ Vérifier le solde total"
echo "   ✅ Consulter l'historique des transactions"
echo "   ✅ Voir les informations de marché"

echo ""
echo "8. 🧪 TEST DES APIS (via navigateur)"
echo "   ✅ Accéder à http://localhost:8001/docs"
echo "   ✅ Tester l'endpoint /api/health"
echo "   ✅ Explorer les endpoints disponibles"

echo ""
echo "9. 📱 TEST RESPONSIVE"
echo "   ✅ Redimensionner la fenêtre du navigateur"
echo "   ✅ Vérifier l'affichage mobile"
echo "   ✅ Tester la navigation sur petit écran"

echo ""
echo "10. 🔄 TEST DE PERSISTENCE"
echo "    ✅ Se déconnecter et se reconnecter"
echo "    ✅ Vérifier que les données sont conservées"
echo "    ✅ Redémarrer les services et retester"

echo ""
echo "✅ SOLDES ATTENDUS APRÈS TOUS LES TESTS:"
echo "   • Inscription: 50 QS"
echo "   • Bonus première connexion: +5 QS"
echo "   • 3 dispositifs enregistrés: +30 QS"
echo "   • 3 heartbeats: +3 QS"
echo "   • TOTAL ATTENDU: ~88 QS"

echo ""
echo "🌟 FONCTIONNALITÉS CLÉS À VALIDER:"
echo "   ✅ Système d'authentification JWT"
echo "   ✅ Cryptographie post-quantique NTRU++"
echo "   ✅ Gestion des dispositifs IoT (3 types)"
echo "   ✅ Économie des tokens avec récompenses"
echo "   ✅ Dashboard temps réel"
echo "   ✅ Interface responsive"
echo "   ✅ Intégration backend-frontend"