# Docker Compose pour QuantumShield
version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: quantumshield-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: quantumshield_phase1

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: quantumshield-backend
    restart: always
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=quantumshield_phase1
      - SECRET_KEY=quantum_shield_phase1_secret_key
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quantumshield-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  mongodb_data: